language: python
os:
  - linux
  - osx
  - windows
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - python setup.py install
# command to run tests
script: pytest
